{
 "title": "clusterpedia-clustersynchro-manager",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "15s, 30s, 1m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "storaged resource total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clustersynchro_resourcesynchro_storaged_resource_total{})[$interval]"
    }
   ]
  },
  {
   "title": "resource max retry total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(clustersynchro_resourcesynchro_resource_max_retry_total{})[$interval]"
    }
   ]
  },
  {
   "title": "dropped resource total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(clustersynchro_resourcesynchro_failed_resource_total{}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "resource added total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(clustersynchro_resourcesynchro_resource_added_total{}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "resource updated total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(increase(clustersynchro_resourcesynchro_resource_updated_total{}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "resource deleted total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(clustersynchro_resourcesynchro_resource_deleted_total{}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "resource failed total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(clustersynchro_resourcesynchro_resource_failed_total{}[$interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99, clustersynchro_resourcesynchro_storage_duration_seconds_bucket{}[$interval]))",
     "legendFormat": "p99"
    },
    {
     "expr": "max(histogram_quantile(0.90, clustersynchro_resourcesynchro_storage_duration_seconds_bucket{}[$interval]))",
     "legendFormat": "p90"
    },
    {
     "expr": "max(histogram_quantile(0.50, clustersynchro_resourcesynchro_storage_duration_seconds_bucket{}[$interval]))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}