apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clusterpedia.apiserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: {{ include "clusterpedia.apiserver.fullname" . }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.apiserver.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app: {{ include "clusterpedia.apiserver.fullname" . }}
  template:
    metadata:
      {{- if .Values.apiserver.podAnnotations }}
      annotations:
      {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app: {{ include "clusterpedia.apiserver.fullname" . }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "clusterpedia.apiserver.imagePullSecrets" . | nindent 6 }}
      initContainers:
    {{- if .Values.externalStorage.createDatabase }}
      - name: ensure-database
        image: {{ include "clusterpedia.storage.image" . }}
        command:
          - /bin/bash
          - -ec
          {{- if eq (include "clusterpedia.storage.type" .) "postgres" }}
          - |
            # Load YAML data into a Bash variable
            if [ -n ${DB_DSN} ]; then source /opt/scripts/parse-yaml.sh; create_variables ${DB_DSN}; fi;
            until psql -U ${DB_USER} -h ${DB_HOST} -p ${DB_PORT} postgres -c "SELECT 1 FROM pg_database WHERE datname = ${DB_DATABASE}" | grep -q 1 || psql -U ${DB_USER} -h ${DB_HOST} -p ${DB_PORT} postgres -c "CREATE DATABASE ${DB_DATABASE} owner ${DB_USER} " -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_DATABASE} to ${DB_USER}"; do
            echo waiting for database check && sleep 1;
            done;
            echo 'DataBase OK ✓'
          {{- else if eq (include "clusterpedia.storage.type" .) "mysql" }}
          - |
            # Load YAML data into a Bash variable
            if [ -n ${DB_DSN} ]; then source /opt/scripts/parse-yaml.sh; create_variables ${DB_DSN}; fi;
            until mysql -u${DB_USER} -p${DB_PASSWORD} --host=${DB_HOST} --port=${DB_PORT} -e "CREATE DATABASE IF NOT EXISTS ${DB_DATABASE}"; do
            echo waiting for database check && sleep 1;
            done;
            echo 'DataBase OK ✓'
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "clusterpedia.internalstorage.fullname" . }}
        env:
          - name: {{ include "clusterpedia.storage.password.envKey" . }}
            valueFrom:
              secretKeyRef:
                name: {{ include "clusterpedia.internalstorage.fullname" . }}
                key: DB_PASSWORD
        volumeMounts:
        - name: scripts
          mountPath: /opt/scripts
          readOnly: true
    {{- else }}
      - name: check-storage
        image: {{ include "clusterpedia.storage.image" . }}
        command: 
          - /bin/bash
          - -ec
          {{- if eq (include "clusterpedia.storage.type" .) "postgres" }}
          - |
            # Load YAML data into a Bash variable
            if [ -n ${DB_DSN} ]; then source /opt/scripts/parse-yaml.sh; create_variables ${DB_DSN}; fi;
            until pg_isready -U ${DB_USER} -d "dbname=${DB_DATABASE}" -h ${DB_HOST} -p ${DB_PORT}; do
            echo waiting for database check && sleep 1; 
            done;
            echo 'DataBase OK ✓'
          {{- else if eq (include "clusterpedia.storage.type" .) "mysql" }}
          - |
            # Load YAML data into a Bash variable
            if [ -n ${DB_DSN} ]; then source /opt/scripts/parse-yaml.sh; create_variables ${DB_DSN}; fi;
            until mysqladmin status -u${DB_USER} -p${DB_PASSWORD} --host=${DB_HOST} --port=${DB_PORT}; do
            echo waiting for database check && sleep 1; 
            done;
            echo 'DataBase OK ✓'
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "clusterpedia.internalstorage.fullname" . }}
        volumeMounts:
        - name: scripts
          mountPath: /opt/scripts
          readOnly: true
    {{- end }}
      containers:
      - name: {{ include "clusterpedia.apiserver.fullname" . }}
        image: {{ template "clusterpedia.apiserver.image" . }}
        imagePullPolicy: {{ .Values.apiserver.image.pullPolicy }}
        command:
        - /usr/local/bin/apiserver
        - --secure-port=443
        - --storage-config=/etc/clusterpedia/storage/internalstorage-config.yaml
        {{- if or (not (empty .Values.apiserver.telemetry.tracing.endpoint)) (not (empty .Values.apiserver.telemetry.tracing.samplingRatePerMillion)) }}
        - --tracing-config-file=/etc/clusterpedia/trace/tracing-config.yaml
        {{- end }}
        {{- with (include "clusterpedia.apiserver.featureGates" .) }}
        - {{ . }}
        {{- end }}
        - -v=3
        {{- if .Values.apiserver.resources }}
        resources: {{- toYaml .Values.apiserver.resources | nindent 12 }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{ include "clusterpedia.internalstorage.fullname" . }}
        env:
        {{- include "clusterpedia.apiserver.tracing.env" . | nindent 8 }}
        {{- if .Values.apiserver.enableSHA1Cert }}
        - name: GODEBUG
          value: netdns=go,x509sha1=1
        {{- else }}
        - name: GODEBUG
          value: netdns=go
        {{- end }}
        volumeMounts:
        - name: internalstorage-config
          mountPath: /etc/clusterpedia/storage
          readOnly: true
        {{- if or (not (empty .Values.apiserver.telemetry.tracing.endpoint)) (not (empty .Values.apiserver.telemetry.tracing.samplingRatePerMillion)) }}
        - name: tracing-config
          mountPath: /etc/clusterpedia/trace
          readOnly: true
        {{- end }}
      serviceAccountName: {{ include "clusterpedia.apiserver.fullname" . }}
      {{- if .Values.apiserver.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiserver.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.apiserver.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.apiserver.tolerations "context" $) | nindent 8 }}
      {{- end }}
      volumes:
        - name: internalstorage-connection-config
          secret:
            secretName: {{ include "clusterpedia.internalstorage.fullname" . }}
        - name: internalstorage-config
          configMap:
            name: {{ include "clusterpedia.internalstorage.fullname" . }}
        - name: scripts
          configMap:
            name: {{ include "clusterpedia.scripts.fullname" . }}
        {{- if or (not (empty .Values.apiserver.telemetry.tracing.endpoint)) (not (empty .Values.apiserver.telemetry.tracing.samplingRatePerMillion)) }}
        - name: tracing-config
          configMap:
            name: {{ include "clusterpedia.apiserver.fullname" .}}-tracing-config
        {{- end }}
