apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.clusterpedia.io
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  insecureSkipTLSVerify: true
  group: clusterpedia.io
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: {{ include "clusterpedia.apiserver.fullname" . }}
    namespace: {{ .Release.Namespace }}
  version: v1beta1
