apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clusterpedia.internalstorage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app: {{ include "clusterpedia.internalstorage.fullname" . }}
    internalstorage.clusterpedia.io/type: {{ include "clusterpedia.storage.type" . }}
data:
  DB_TYPE: {{ include "clusterpedia.storage.type" . | b64enc | quote}}
{{- if empty (include "clusterpedia.storage.dsn" .) }}
  DB_HOST: {{ include "clusterpedia.storage.host" . | b64enc }}
  DB_PORT: "{{ include "clusterpedia.storage.port" . | b64enc }}"
  DB_USER: "{{ include "clusterpedia.storage.user" . | b64enc }}"
  DB_DATABASE: {{ include "clusterpedia.storage.database" . | b64enc }}
  DB_PASSWORD: {{ include "clusterpedia.storage.password" . | b64enc }}
{{- else }}
  DB_DSN: {{ include "clusterpedia.storage.dsn" . | b64enc | quote}}
{{- end }}