apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clusterpedia.scripts.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  parse-yaml.sh: |
    function parse_mysql_dsn() {
        local dsn=$1
        if [ -z $dsn ]
        then
            return
        fi

        IFS='?' read -r -a _dsn <<< $dsn; upnad=${_dsn[0]}
        IFS='/' read -a upnad <<< $upnad; upna=${upnad[0]}; database=${upnad[1]}
        IFS='(' read -a upna <<< $upna ; upn=${upna[0]}; address=${upna[1]%?}
        IFS='@' read -r -a upn <<< $upn; up=${upn[0]}; protocal=${upn[1]}
        IFS=':' read -r -a up <<< $up; user=${up[0]}; password=${up[1]}

        if [ ! -z $address ]
        then
            IFS=':' read -r -a address <<< $address; host=${address[0]}; port=${address[1]}
        fi

        echo "DB_DATABASE=\"$database\""
        echo "DB_HOST=\"$host\""
        echo "DB_PORT=\"$port\""
        echo "DB_USER=\"$user\""
        echo "DB_PASSWORD=\"$password\""
    }
    
    function parse_postgres_dsn() {
        local dsn=$1
        if [ -z $dsn ]
        then
            return
        fi

        kvpairs=($dsn)
        for kv in "${kvpairs[@]}"; do
            if [[ $kv == "host"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; host=${_kv[1]}
            fi
            if [[ $kv == "user"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; user=${_kv[1]}
            fi
            if [[ $kv == "password"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; password=${_kv[1]}
            fi
            if [[ $kv == "port"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; port=${_kv[1]}
            fi
            if [[ $kv == "dbname"* ]]; then
            IFS='=' read -r -a _kv <<< $kv; database=${_kv[1]}
            fi
        done
    
        echo "DB_DATABASE=\"$database\""
        echo "DB_HOST=\"$host\""
        echo "DB_PORT=\"$port\""
        echo "DB_USER=\"$user\""
        echo "PGPASSWORD=\"$password\""
    }

    function create_variables() {
        if [ $DB_TYPE == "mysql" ]
        then
            eval $(parse_mysql_dsn "$DB_DSN")
        fi
    
        if [ $DB_TYPE == "postgres" ]
        then
            eval $(parse_postgres_dsn "$DB_DSN")
        fi
    }
